### ISSUE TITLE
Integrating Drag Drop

### ISSUE THREAD

**Issue by xanpj** [pinussilvestrus/postit-js#22]
Let's think of a Drag n Drop Image Feature. What is the best place to integrate it in the lib? PostitEditorActions, PostitRules...?
With Base64 encoded upload for now.

<img width="1280" alt="Screen Shot 2020-06-05 at 6 02 41 PM" src="https://user-images.githubusercontent.com/3321506/83898129-c7d6f180-a756-11ea-8827-dc42ace7a74d.png">

**Comment by pinussilvestrus** [comment]
Interesting Feature! I think it should have been an own feature module `dropImage` for that purpose, which does

* detecting an image file has been dropped on the canvas, there is currently no event for this, but should be straight forward with any drag and drop approach
* creating a new image element via ElementFactory

Therefore the image would have to be uploaded somewhere since it's only storing an source url currently for Rendering the image.

**Comment by xanpj** [comment]
I got the mentioned steps working already. Just not sure were to put the code to align with the structrue. Should `dropImage` become a `feature/` module?

**Comment by pinussilvestrus** [comment]
Yep, exactly! Feel free to open a PR :)

**Comment by xanpj** [comment]
I have uploaded the feature as a module in https://github.com/xanpj/postit-js-extensions
